- hosts: localhost
  vars:
    user: "{{ ansible_user_id }}"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present

  tasks:
    - name: Install production repository
      become: true
      shell: curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

    - name: Update the packages list
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present

    - name: Install NVidia Container toolkit
      become: true
      shell: apt-get install -y nvidia-container-toolkit

    - name: Configure container using nvidia-ctk
      become: true
      shell: nvidia-ctk runtime configure --runtime=docker
