- name: Check for cargo
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes
  tags:
    - productivity
    - alacritty

- name: Download Rust install script
  when: cargo_exists == false
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - productivity
    - alacritty

- name: Install rust/cargo
  when: cargo_exists == false
  shell: /tmp/sh.rustup.rs -y
  tags:
    - productivity
    - alacritty

- name: Source rustc/cargo/zsh
  when: cargo_exists == false
  shell: source $HOME/.cargo/bin && source ~/.zshrc
  tags:
    - productivity
    - alacritty

- name: Install dependencies
  become: true
  apt:
    name: [ libfreetype6-dev, libfontconfig1-dev, libxcb-xfixes0-dev, libxkbcommon-dev ]
  tags:
    - productivity
    - alacritty

- name: Remove Alacritty
  become: true
  file:
    path: "{{ lookup('env', 'HOME') }}/alacritty"
    state: absent
  tags:
    - productivity
    - alacritty

- name: Clone Alacritty
  ansible.builtin.git:
    repo: "https://github.com/alacritty/alacritty.git"
    dest: "~/alacritty/"
  tags:
    - productivity
    - alacritty

- name: Build Alacritty
  shell: cd ~/alacritty && cargo build --release
  tags:
    - productivity
    - alacritty

- name: Copy Binary to bin
  become: true
  shell: cp {{ lookup('env', 'HOME') }}/alacritty/target/release/alacritty /usr/local/bin
  tags:
    - productivity
    - alacritty

- name: Copy logo and Setup desktop
  become: true
  shell: cp {{ lookup('env', 'HOME') }}/alacritty/extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg && desktop-file-install {{ lookup('env', 'HOME') }}/alacritty/extra/linux/Alacritty.desktop && update-desktop-database
  tags:
    - productivity
    - alacritty

- name: Copy settings from dotfiles
  shell: cd {{ lookup('env', 'HOME') }}/.dotfiles && stow alacritty
  ignore_errors: yes
  tags:
    - productivity
    - alacritty

- name: Install Manual Page
  become: true
  shell: mkdir -p /usr/local/share/man/man1 && mkdir -p /usr/local/share/man/man5 && scdoc < extra/man/alacritty.1.scd | gzip -c | sudo tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null && scdoc < extra/man/alacritty-msg.1.scd | gzip -c | sudo tee /usr/local/share/man/man1/alacritty-msg.1.gz > /dev/null && scdoc < extra/man/alacritty.5.scd | gzip -c | sudo tee /usr/local/share/man/man5/alacritty.5.gz > /dev/null && scdoc < extra/man/alacritty-bindings.5.scd | gzip -c | sudo tee /usr/local/share/man/man5/alacritty-bindings.5.gz > /dev/null
  tags:
    - productivity
    - alacritty

- name: Add shell completions
  shell: mkdir -p {{ lookup('env', 'HOME') }}/.zsh_functions/ && cp {{ lookup('env', 'HOME') }}/alacritty/extra/completions/_alacritty {{ lookup('env', 'HOME') }}/.zsh_functions/_alacritty
  tags:
    - productivity
    - alacritty
