- name: Installing stow
  become: true
  apt:
    name: stow
  tags:
    - install

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:FooNameBar/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./setupVars
  tags:
    - install

