- name: Installing stow
  become: true
  apt:
    name: stow
  tags:
    - install

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:FooNameBar/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    single_branch: yes
    version: docker
  tags:
    - install

- name: Stow dotfiles
  shell: "{{ lookup('env', 'HOME') }}/.dotfiles/setupVars && source {{ lookup('env', 'HOME') }}/.zshrc"
  tags:
    - install

