- name: Use stat to check .ssh exists
  stat:
    path: "{{ dest_key | dirname }}"
  register: dir_data
  tags:
    - install

- name: Creating .ssh
  file:
    dest: "{{ dest_key | dirname }}"
    state: directory
    mode: '0700'
  tags:
    - install

- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: '0600'
  tags:
    - install

- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: '0644'
  tags:
    - install

- name: Cat public keys into register
  command: cat "{{ item }}"
  register: keys
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
  tags:
    - install

- name: Set authorized keys from files
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ item.stdout }}"
  with_items: "{{ keys.results }}"
  tags:
    - install
